try:
 x=10
 exit()

except ValueError as e:
 print("Some problem")